version: '3.7'

volumes:
  icanyii_data:
  icanyii_redis:

networks:
  app:
    ipam:
      driver: default
      config:
        - subnet: 129.18.3.0/24

services:
  app:
    build:
      context: .
#   restart: always
    volumes:
      - ./:/var/www/html
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1"
      PHP_IDE_CONFIG: "serverName=icanyii"
    env_file:
      - .env
    networks:
      app:
        ipv4_address: 129.18.3.10

  web:
    image: nginx:1.19.2
#   restart: always
    ports:
      - 80:80
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    networks:
      app:
        ipv4_address: 129.18.3.11

  db:
    image: mysql:5.7.32
#   restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - icanyii_data:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    networks:
      app:
        ipv4_address: 129.18.3.12

  redis:
    image: redis:6.0.9
#   restart: always
    ports:
      - 6379:6379
    volumes:
      - icanyii_redis:/var/lib/redis
    networks:
      app:
        ipv4_address: 129.18.3.13
